### ISSUE TITLE
Hum

### ISSUE THREAD

**Issue by CookieCode** [armagadon159753/skyblock#1]
Please upload it in folders.

**Comment by armagadon159753** [comment]
Sorry i m on Android ans i cant upload un folder structure otherwise I will have done it

**Comment by optimusprime338** [comment]
good job sir, Thanks.. was searching for a developer for our server . its one of top 15 servers.. would be happy if we get ur in our team!!!!

**Comment by armagadon159753** [comment]
@optimusprime338 why not

**Comment by optimusprime338** [comment]
join our discord team :- https://discordapp.com/invite/bKqdF6q
